#if SOKUTEI_OS_TYPE == SOKUTEI_MACOS

#ifndef SOKUTEI_SOKUTEI_MACOS_H
#define SOKUTEI_SOKUTEI_MACOS_H

#   ifndef SOKUTEI_CUSTOM_TIMER
#   endif //SOKUTEI_CUSTOM_TIMER
#endif //CONDITIONAL
#endif //SOKUTEI_SOKUTEI_MACOS_H
